export type Plant = {
  id: number;
  title: string;
  description: string;
  category: string;
  stars: number;
  image: any;
  price: number;
  careLevel: "Easy" | "Moderate" | "Expert";
  light: "Low" | "Medium" | "Bright";
  water: "Low" | "Weekly" | "Frequent";
  petFriendly: boolean;
  size: "Small" | "Medium" | "Large";
  stock: number;
};

export type CartItem = Plant & { quantity: number };

const plantData: Plant[] = [
  {
    id: 1,
    title: "Succulent",
    description:
      "A compact, drought-tolerant succulent that thrives in patio containers with good drainage. Its plump leaves store water, so it forgives the occasional missed watering. Perfect for sunny balconies and low-effort greenery.",
    category: "Patio",
    stars: 4.5,
    image: require("@/assets/plants/7.jpeg"),
    price: 25.99,
    careLevel: "Easy",
    light: "Bright",
    water: "Low",
    petFriendly: true,
    size: "Small",
    stock: 18,
  },
  {
    id: 2,
    title: "Fiddle Leaf Fig",
    description:
      "A designer favorite with large, violin-shaped leaves that make a bold statement indoors. It loves bright, indirect light and a consistent watering routine. Rotate it occasionally so it grows evenly toward the light.",
    category: "Indoor",
    stars: 4.7,
    image: require("@/assets/plants/8.jpeg"),
    price: 45.5,
    careLevel: "Moderate",
    light: "Bright",
    water: "Weekly",
    petFriendly: false,
    size: "Large",
    stock: 7,
  },
  {
    id: 3,
    title: "Palm Branch",
    description:
      "A leafy palm that brings an instant tropical vibe to outdoor spaces. It handles warm, humid conditions with ease and rewards you with lush, arching fronds. Give it dappled sun and room to spread.",
    category: "Outdoor",
    stars: 4.3,
    image: require("@/assets/plants/1.jpeg"),
    price: 30.0,
    careLevel: "Moderate",
    light: "Bright",
    water: "Weekly",
    petFriendly: true,
    size: "Large",
    stock: 5,
  },
  {
    id: 4,
    title: "Bird of Paradise",
    description:
      "An elegant, vibrant statement plant known for its striking paddle-shaped leaves and exotic blooms. Given enough light and warmth, it can grow into a dramatic focal point. A true showpiece for patios and bright corners.",
    category: "Outdoor",
    stars: 4.8,
    image: require("@/assets/plants/2.jpeg"),
    price: 60.75,
    careLevel: "Expert",
    light: "Bright",
    water: "Frequent",
    petFriendly: false,
    size: "Large",
    stock: 0,
  },
  {
    id: 5,
    title: "Artificial Fiddle Leaf",
    description:
      "All the drama of a fiddle leaf fig with zero maintenance. This lifelike artificial plant keeps its lush look year-round without water or light. Ideal for dim rooms, offices, or anyone short on time.",
    category: "Indoor",
    stars: 4.6,
    image: require("@/assets/plants/3.jpeg"),
    price: 20.99,
    careLevel: "Easy",
    light: "Low",
    water: "Low",
    petFriendly: true,
    size: "Large",
    stock: 25,
  },
  {
    id: 6,
    title: "Succulent Vase",
    description:
      "A compact, stylish arrangement of succulents in a decorative vase. It makes a charming patio or windowsill accent and asks for very little attention. Just a splash of water now and then keeps it happy.",
    category: "Patio",
    stars: 4.4,
    image: require("@/assets/plants/4.jpeg"),
    price: 15.49,
    careLevel: "Easy",
    light: "Bright",
    water: "Low",
    petFriendly: true,
    size: "Small",
    stock: 30,
  },
  {
    id: 7,
    title: "Leafy Green",
    description:
      "A fresh, vibrant foliage plant that adds instant life to any garden bed. It grows quickly in rich soil with regular watering. A reliable, cheerful filler for borders and containers.",
    category: "Garden",
    stars: 4.2,
    image: require("@/assets/plants/5.jpeg"),
    price: 18.25,
    careLevel: "Easy",
    light: "Medium",
    water: "Weekly",
    petFriendly: true,
    size: "Medium",
    stock: 14,
  },
  {
    id: 8,
    title: "Artificial Palm",
    description:
      "A tropical, evergreen palm replica that stays picture-perfect in every season. No trimming, watering, or sunlight required — just set it and enjoy. Great for shaded patios and interior corners alike.",
    category: "Outdoor",
    stars: 4.9,
    image: require("@/assets/plants/6.jpeg"),
    price: 50.0,
    careLevel: "Easy",
    light: "Low",
    water: "Low",
    petFriendly: true,
    size: "Large",
    stock: 9,
  },
  {
    id: 9,
    title: "Monstera Deliciosa",
    description:
      "The iconic split-leaf beauty loved for its dramatic, fenestrated foliage. It's an easygoing climber that thrives in bright, indirect light. Give it a moss pole and watch it flourish.",
    category: "Indoor",
    stars: 4.7,
    image: require("@/assets/plants/9.jpeg"),
    price: 35.99,
    careLevel: "Easy",
    light: "Medium",
    water: "Weekly",
    petFriendly: false,
    size: "Medium",
    stock: 11,
  },
  {
    id: 10,
    title: "Snake Plant",
    description:
      "An air-purifying champion that tolerates neglect like a pro. Its upright, sword-like leaves suit modern interiors and low-light corners. Water sparingly — it prefers to dry out between drinks.",
    category: "Indoor",
    stars: 4.6,
    image: require("@/assets/plants/10.jpeg"),
    price: 22.5,
    careLevel: "Easy",
    light: "Low",
    water: "Low",
    petFriendly: false,
    size: "Medium",
    stock: 20,
  },
  {
    id: 11,
    title: "Peace Lily",
    description:
      "Elegant white blooms and glossy green leaves make this a garden and indoor favorite. It signals when it's thirsty by drooping, then perks right back up after watering. Enjoys shade and consistent moisture.",
    category: "Garden",
    stars: 4.8,
    image: require("@/assets/plants/11.jpeg"),
    price: 28.75,
    careLevel: "Moderate",
    light: "Low",
    water: "Frequent",
    petFriendly: false,
    size: "Medium",
    stock: 8,
  },
  {
    id: 12,
    title: "Rubber Plant",
    description:
      "Glossy, deep-green leaves give this plant a bold, sculptural presence. It grows tall over time, offering natural indoor privacy. Wipe the leaves occasionally to keep them shining.",
    category: "Indoor",
    stars: 4.5,
    image: require("@/assets/plants/12.jpeg"),
    price: 32.99,
    careLevel: "Easy",
    light: "Medium",
    water: "Weekly",
    petFriendly: false,
    size: "Large",
    stock: 10,
  },
  {
    id: 13,
    title: "ZZ Plant",
    description:
      "Nearly indestructible, the ZZ plant shrugs off low light and irregular watering. Its waxy, dark-green leaves add a polished look to any room. The perfect pick for beginners and busy plant parents.",
    category: "Indoor",
    stars: 4.9,
    image: require("@/assets/plants/13.jpeg"),
    price: 26.5,
    careLevel: "Easy",
    light: "Low",
    water: "Low",
    petFriendly: false,
    size: "Medium",
    stock: 16,
  },
  {
    id: 14,
    title: "Pothos",
    description:
      "A trailing vine beauty that's happiest cascading from a shelf or hanging basket. It's forgiving, fast-growing, and easy to propagate from cuttings. Thrives in a wide range of light conditions.",
    category: "Indoor",
    stars: 4.4,
    image: require("@/assets/plants/14.jpeg"),
    price: 18.99,
    careLevel: "Easy",
    light: "Medium",
    water: "Weekly",
    petFriendly: false,
    size: "Small",
    stock: 22,
  },
  {
    id: 15,
    title: "Aloe Vera",
    description:
      "A healing succulent prized for its soothing gel and sculptural rosette of leaves. It loves sunny patio spots and needs very little water. Keep it in well-draining soil and bright light.",
    category: "Patio",
    stars: 4.7,
    image: require("@/assets/plants/15.jpeg"),
    price: 19.75,
    careLevel: "Easy",
    light: "Bright",
    water: "Low",
    petFriendly: false,
    size: "Small",
    stock: 19,
  },
  {
    id: 16,
    title: "Spider Plant",
    description:
      "An easy, adaptable garden favorite that sends out charming baby plantlets. It's simple to propagate and quickly fills out a pot or border. Tolerant of most conditions and great for beginners.",
    category: "Garden",
    stars: 4.3,
    image: require("@/assets/plants/16.jpeg"),
    price: 15.99,
    careLevel: "Easy",
    light: "Medium",
    water: "Weekly",
    petFriendly: true,
    size: "Small",
    stock: 27,
  },
  {
    id: 17,
    title: "Bamboo Palm",
    description:
      "A graceful palm that brings tropical elegance to garden corners and shaded patios. Its slender canes and feathery fronds create a lush, layered look. Keep the soil evenly moist for best growth.",
    category: "Garden",
    stars: 4.6,
    image: require("@/assets/plants/17.jpeg"),
    price: 42.5,
    careLevel: "Moderate",
    light: "Medium",
    water: "Weekly",
    petFriendly: true,
    size: "Large",
    stock: 6,
  },
  {
    id: 18,
    title: "Dracaena",
    description:
      "Striking, sword-like foliage with colorful edges makes Dracaena a standout in garden borders. It's low-maintenance and tolerant of varied light. Avoid overwatering to keep the roots healthy.",
    category: "Garden",
    stars: 4.5,
    image: require("@/assets/plants/18.jpeg"),
    price: 29.99,
    careLevel: "Easy",
    light: "Medium",
    water: "Low",
    petFriendly: false,
    size: "Medium",
    stock: 12,
  },
  {
    id: 19,
    title: "Ficus Lyrata",
    description:
      "A large-leaved statement piece that anchors spacious indoor rooms with style. It appreciates bright, indirect light and steady watering. Give it space to reach its full, tree-like potential.",
    category: "Indoor",
    stars: 4.8,
    image: require("@/assets/plants/19.jpeg"),
    price: 55.0,
    careLevel: "Expert",
    light: "Bright",
    water: "Weekly",
    petFriendly: false,
    size: "Large",
    stock: 0,
  },
  {
    id: 20,
    title: "Calathea",
    description:
      "A prayer plant with beautifully patterned leaves that fold up at night. It thrives in shaded, humid garden areas and consistent moisture. Reward it with humidity and it'll reward you with vivid foliage.",
    category: "Garden",
    stars: 4.4,
    image: require("@/assets/plants/20.jpeg"),
    price: 24.5,
    careLevel: "Expert",
    light: "Low",
    water: "Frequent",
    petFriendly: true,
    size: "Medium",
    stock: 9,
  },
  {
    id: 21,
    title: "Philodendron",
    description:
      "Heart-shaped leaves and a trailing habit make Philodendron a versatile garden and indoor grower. It's forgiving, fast, and perfect as ground cover or a hanging accent. Thrives with minimal fuss.",
    category: "Garden",
    stars: 4.7,
    image: require("@/assets/plants/21.jpeg"),
    price: 27.99,
    careLevel: "Easy",
    light: "Medium",
    water: "Weekly",
    petFriendly: false,
    size: "Medium",
    stock: 15,
  },
  {
    id: 22,
    title: "Chinese Evergreen",
    description:
      "Colorful, patterned foliage brings a decorative pop to garden accents and shady spots. It's remarkably tolerant of low light and irregular care. A hardy choice that stays attractive year-round.",
    category: "Garden",
    stars: 4.5,
    image: require("@/assets/plants/22.jpeg"),
    price: 23.75,
    careLevel: "Easy",
    light: "Low",
    water: "Weekly",
    petFriendly: false,
    size: "Medium",
    stock: 13,
  },
  {
    id: 23,
    title: "Jade Plant",
    description:
      "A lucky succulent with thick, glossy leaves and a tree-like form. It loves sunny patio spots and needs only occasional watering. Slow-growing and long-lived, it's a rewarding companion.",
    category: "Patio",
    stars: 4.6,
    image: require("@/assets/plants/23.jpeg"),
    price: 20.99,
    careLevel: "Easy",
    light: "Bright",
    water: "Low",
    petFriendly: false,
    size: "Small",
    stock: 21,
  },
  {
    id: 24,
    title: "Areca Palm",
    description:
      "Feathery, arching fronds make the Areca Palm a lush choice for outdoor privacy screens. It thrives in bright, filtered light and regular watering. A vibrant way to green up a patio or garden edge.",
    category: "Outdoor",
    stars: 4.7,
    image: require("@/assets/plants/24.jpeg"),
    price: 38.5,
    careLevel: "Moderate",
    light: "Bright",
    water: "Weekly",
    petFriendly: true,
    size: "Large",
    stock: 4,
  },
];

export default plantData;