export type Plant = {
  id: number;
  title: string;
  description: string;
  category: string;
  stars: number;
  image: any;
  price: number;
};

const plantData: Plant[] = [
  {
    id: 1,
    title: "Succulent",
    description: "Thrives in patio containers with good drainage.",
    category: "Patio",
    stars: 4.5,
    image: require("@/assets/plants/7.jpeg"),
    price: 25.99,
  },
  {
    id: 2,
    title: "Fiddle Leaf Fig",
    description: "Perfect for indoor spaces with bright, indirect light.",
    category: "Indoor",
    stars: 4.7,
    image: require("@/assets/plants/8.jpeg"),
    price: 45.50,
  },
  {
    id: 3,
    title: "Palm Branch",
    description: "Adds a tropical vibe to outdoor spaces.",
    category: "Outdoor",
    stars: 4.3,
    image: require("@/assets/plants/1.jpeg"),
    price: 30.00,
  },
  {
    id: 4,
    title: "Bird of Paradise",
    description: "Elegant and vibrant outdoor statement plant.",
    category: "Outdoor",
    stars: 4.8,
    image: require("@/assets/plants/2.jpeg"),
    price: 60.75,
  },
  {
    id: 5,
    title: "Artificial Fiddle Leaf",
    description: "Low maintenance beauty for any indoor space.",
    category: "Indoor",
    stars: 4.6,
    image: require("@/assets/plants/3.jpeg"),
    price: 20.99,
  },
  {
    id: 6,
    title: "Succulent Vase",
    description: "Compact and stylish patio accent.",
    category: "Patio",
    stars: 4.4,
    image: require("@/assets/plants/4.jpeg"),
    price: 15.49,
  },
  {
    id: 7,
    title: "Leafy Green",
    description: "Fresh and vibrant garden addition.",
    category: "Garden",
    stars: 4.2,
    image: require("@/assets/plants/5.jpeg"),
    price: 18.25,
  },
  {
    id: 8,
    title: "Artificial Palm",
    description: "Tropical and evergreen outdoor statement.",
    category: "Outdoor",
    stars: 4.9,
    image: require("@/assets/plants/6.jpeg"),
    price: 50.00,
  },
  {
    id: 9,
    title: "Monstera Deliciosa",
    description: "Iconic split-leaf beauty for indoor spaces.",
    category: "Indoor",
    stars: 4.7,
    image: require("@/assets/plants/9.jpeg"),
    price: 35.99,
  },
  {
    id: 10,
    title: "Snake Plant",
    description: "Air-purifying champion for any indoor space.",
    category: "Indoor",
    stars: 4.6,
    image: require("@/assets/plants/10.jpeg"),
    price: 22.50,
  },
  {
    id: 11,
    title: "Peace Lily",
    description: "Elegant white blooms for garden beds.",
    category: "Garden",
    stars: 4.8,
    image: require("@/assets/plants/11.jpeg"),
    price: 28.75,
  },
  {
    id: 12,
    title: "Rubber Plant",
    description: "Glossy dark leaves for indoor privacy.",
    category: "Indoor",
    stars: 4.5,
    image: require("@/assets/plants/12.jpeg"),
    price: 32.99,
  },
  {
    id: 13,
    title: "ZZ Plant",
    description: "Nearly indestructible indoor companion.",
    category: "Indoor",
    stars: 4.9,
    image: require("@/assets/plants/13.jpeg"),
    price: 26.50,
  },
  {
    id: 14,
    title: "Pothos",
    description: "Trailing vine beauty for indoor hanging baskets.",
    category: "Indoor",
    stars: 4.4,
    image: require("@/assets/plants/14.jpeg"),
    price: 18.99,
  },
  {
    id: 15,
    title: "Aloe Vera",
    description: "Healing succulent for sunny patio spots.",
    category: "Patio",
    stars: 4.7,
    image: require("@/assets/plants/15.jpeg"),
    price: 19.75,
  },
  {
    id: 16,
    title: "Spider Plant",
    description: "Easy to propagate garden favorite.",
    category: "Garden",
    stars: 4.3,
    image: require("@/assets/plants/16.jpeg"),
    price: 15.99,
  },
  {
    id: 17,
    title: "Bamboo Palm",
    description: "Tropical elegance for garden corners.",
    category: "Garden",
    stars: 4.6,
    image: require("@/assets/plants/17.jpeg"),
    price: 42.50,
  },
  {
    id: 18,
    title: "Dracaena",
    description: "Striking foliage for garden borders.",
    category: "Garden",
    stars: 4.5,
    image: require("@/assets/plants/18.jpeg"),
    price: 29.99,
  },
  {
    id: 19,
    title: "Ficus Lyrata",
    description: "Statement piece for large indoor spaces.",
    category: "Indoor",
    stars: 4.8,
    image: require("@/assets/plants/19.jpeg"),
    price: 55.00,
  },
  {
    id: 20,
    title: "Calathea",
    description: "Prayer plant beauty for shaded garden areas.",
    category: "Garden",
    stars: 4.4,
    image: require("@/assets/plants/20.jpeg"),
    price: 24.50,
  },
  {
    id: 21,
    title: "Philodendron",
    description: "Heart-shaped leaves for garden ground cover.",
    category: "Garden",
    stars: 4.7,
    image: require("@/assets/plants/21.jpeg"),
    price: 27.99,
  },
  {
    id: 22,
    title: "Chinese Evergreen",
    description: "Colorful foliage for garden accents.",
    category: "Garden",
    stars: 4.5,
    image: require("@/assets/plants/22.jpeg"),
    price: 23.75,
  },
  {
    id: 23,
    title: "Jade Plant",
    description: "Lucky succulent for sunny patio spots.",
    category: "Patio",
    stars: 4.6,
    image: require("@/assets/plants/23.jpeg"),
    price: 20.99,
  },
  {
    id: 24,
    title: "Areca Palm",
    description: "Feathery fronds for outdoor privacy.",
    category: "Outdoor",
    stars: 4.7,
    image: require("@/assets/plants/24.jpeg"),
    price: 38.50,
  }
];

export default plantData;